import Image from "next/image";
import Logo from "@/components/logo";
import "../globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ConvexClientProvider } from "../ConvexClientProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function AuthLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ConvexClientProvider>
                    <div className="grid min-h-svh lg:grid-cols-2 font-sans">
                        <div className="flex flex-col gap-4 p-6 md:p-10">
                            <div className="flex justify-center gap-2 md:justify-start mb-8">
                                <Logo size={44} link={false} />
                                <span className="text-2xl font-bold text-blue-700 tracking-tight">Gloria Connect</span>
                            </div>
                            <div className="flex flex-1 items-center justify-center">
                                <div className="w-full max-w-xs">
                                    {children}
                                </div>
                            </div>
                        </div>
                        <div className="bg-muted relative hidden lg:block">
                            <div className="absolute inset-0 w-full h-full z-10 flex flex-col items-center justify-center">
                                <div className="bg-white/80 backdrop-blur-sm px-10 py-8 rounded-2xl shadow-lg">
                                    <h2 className="text-7xl font-extrabold text-green-700 drop-shadow-lg text-center mb-4">
                                        Welcome to Gloria!<br />
                                        <span className="text-4xl font-semibold text-green-900">Ngani Mandin!</span>
                                    </h2>
                                </div>
                            </div>
                            <Image
                                src="https://lh6.googleusercontent.com/proxy/SSlbN_xPSedpJBBNJf6sjrsnhmYyhfBSa-CzQtfbacKLFqs4MKppNb1-fEoz_op1D1Li8M9r997Iqowz46prSV0qnESoQCvJv8U6ankBxOd-"
                                alt="Authentication illustration"
                                fill
                                style={{ objectFit: "cover" }}
                                className="opacity-60 dark:brightness-[0.2] dark:grayscale"
                                priority
                            />
                        </div>
                    </div>
                </ConvexClientProvider>
            </body>
        </html>
    );
}
