import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ConvexClientProvider } from "../convex-client-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { I18nProvider } from "./i18n-provider";
import enMessages from "../../../messages/en.json";
import filMessages from "../../../messages/fil.json";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const language = "en";
  const messages = language === "fil" ? filMessages : enMessages;

  return (
    <ConvexClientProvider>
      <I18nProvider language={language} messages={messages}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </I18nProvider>
    </ConvexClientProvider>
  );
}
